name: Odoo18 CICD for RAWCS

on:
  push:
    branches:
      - main  # Change if using another branch ---Keep if deploying other modules from the main branch

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget git python3-dev python3-pip build-essential libxslt1-dev libzip-dev libldap2-dev libsasl2-dev python3-setuptools node-less libjpeg-dev libpq-dev

      - name: Create a virtual environment
        run: |
            python -m venv /opt/odoo/venv
            source /opt/odoo/venv/bin/activate
            pip install --upgrade pip  
            pip install wheel cryptography  

      - name: 🔑 Set Up SSH Connection
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
              echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
              eval "$(ssh-agent -s)"
              ssh-add private_key
          
      - name: ✅ Test SSH Connection
        run: |
             ssh -i private_key -o StrictHostKeyChecking=no ubuntu@45.113.8.66 "echo '✅ SSH Connection Successful!'"
          
      - name: Install Python dependencies on Odoo server
        run: |
              ssh -i private_key -o StrictHostKeyChecking=no ubuntu@45.113.8.66 << 'EOF'
              python3 -m venv /home/ubuntu/venv
              source /home/ubuntu/venv/bin/activate
              pip install --upgrade pip
              pip install openpyxl qifparse pyfcm httpagentparser dropbox pyncclient nextcloud-api-wrapper boto3 paramiko
              EOF

      - name: 📂 Deploy Module to Odoo Server
        run: |
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/account_move_multi_cancel ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/app_menu_alphabetical_order ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/auto_daily_weekly_report ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/auto_database_backup ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/odoo_dynamic_dashboard ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/odoo_google_meet_integration ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/odoo_website_helpdesk ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/odoo_website_helpdesk_dashboard ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/openai_odoo_base ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/partner_emails_history ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/project_dashboard_odoo ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/project_progress_bar ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/public_helpdesk ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/rotary_project_map ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/schedule_activity_to_multiple_users ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/size_restriction_for_attachments ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/subscription_package ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/users_ldap_mail ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/volunteers_donors_management ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/website_event ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/website_gdpr_odoo ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/website_pdf_preview_snippet ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/whatsapp_mail_messaging ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/whatsapp_redirect ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/base_account_budget ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/base_accounting_kit ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/base_user_role ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/bi_sms_client_generic ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/contact_documents ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/contacts_birthday_greetings ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/database_delete_protection ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/easy_chatgpt_access ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/education_core ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/education_theme ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/event ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/excel_report_designer ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/ica_web_responsive ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/insurance_management_cybro ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/ldap_reset_password ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/master_search ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/membership ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/membership_rotary_modifications ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/
              scp -i private_key -o StrictHostKeyChecking=no -r ./addons/mass-mailing ubuntu@45.113.8.66:/opt/odoo18/odoo18-addons/


      - name: Start Odoo Server
        run: |
              ssh -i private_key -o StrictHostKeyChecking=no ubuntu@45.113.8.66 "sudo systemctl start odoo18"
